#!/usr/bin/env python3
"""Manual Testing Guide v1.20.9 (Taglish). usage: python3 tools/release-docs/make-guide-v1.20.9.py ; node tools/release-docs/html-to-pdf.js <html> <pdf>"""
exec(open('tools/release-docs/make-report-v1.20.9.py').read().split('import re,os')[0])
G=[]
G.append('<h1>Logic Sim v%s - Manual Testing Guide</h1><small>Para sa non-coder. Petsa: %s. Gamitin ang HTML: <a href="%slogic-sim-v%s.html">%slogic-sim-v%s.html</a> sa Chrome.</small>'%(V,DATE,DL,V,DL,V))
G.append('<div class="box"><b>Paano gamitin:</b> Gawin ang bawat test ayon sa hakbang. Isulat ang nakita mo sa "Actual result mo" at lagyan ng PASS o FAIL. Kung hindi tugma, gawin ang nasa "Kapag hindi tugma". Lahat ay <b>NOT TESTED</b> hanggang magawa mo. Ang "Rehearsal result" ay ang nakita ko sa headless browser; hindi iyon ang test mo.<br><b>Mga salita:</b> <b>Run</b> = pindutin ang <code>▶ Run</code> sa taas. <b>Panel</b> = ang kanang bahagi ng screen. <b>FORCE</b> = kahon sa Panel na may <code>✓</code> (ilagay ang numero, pindutin ang ✓) at <code>✕</code> (alisin ang force). Para pumili ng wire o block: i-click ito sa diagram. Ang sheet ay pinipili sa listahan sa kaliwa (hal. "ABC-002").</div>')
def mt(i,sheet,block,start,steps,expected,rehearsal,bad):
    o='<h3>%s - %s</h3>'%(i,e(sheet))
    o+=table(['Item','Detalye'],[['Sheet',sheet],['Block / tag',block],['Starting condition',start],['Mga hakbang','<ol>'+''.join('<li>%s</li>'%s for s in steps)+'</ol>'],['Inaasahang resulta',expected],['Rehearsal result (ako, hindi mo test)',rehearsal],['Actual result mo','&nbsp;<br>&nbsp;'],['Status','<b>NOT TESTED</b> (gawing PASS o FAIL pagkatapos)'],['Kapag hindi tugma',bad]],raw=True)
    return o
G.append(mt('MT-01','Kahit anong ABC sheet','Toolbar sa taas','Bagong bukas na HTML.',['Buksan ang HTML sa Chrome.','Pindutin ang <b>Analog · ABC</b>.','Tingnan ang toolbar sa taas.'],'WALA ang: Save, Save as, Open, Import ABC DXF, Imports, Plant. MAYROON ang: View, Run, Reset, Fit, Values, <b>Wire values</b>, <b>Review marks</b>, Health, LN tables, Assumed values, DITL signals.','Wala ang mga inalis; naroon ang Wire values at Review marks; walang error banner.','Kung may Save/Open/Import/Plant o kulang ang dalawang bagong button: FAIL, screenshot.'))
G.append(mt('MT-02','ABC-002','Transmitter AI0273 (AT-FG1122), range 0 ~ 25 %','Pindutin ang <code>▶ Run</code>. Walang force.',['Piliin ang sheet <b>ABC-002</b> at pindutin ang Run.','I-click ang tatsulok na <b>AI</b> sa ilalim ng "FLUE GAS O2 (A)" (may nakasulat na AI0273 sa kanan).','Sa Panel, hanapin ang linyang <b>OUT AI0273</b> na may kahon ng numero.','I-type ang <b>15</b> at pindutin ang <b>✓</b>.','Tingnan ang numero sa tabi ng <b>AI0273</b>, sa tabi ng <b>AT-FG1122</b> at sa loob/tabi ng <b>ALM</b> box.','I-type ang <b>99</b> at pindutin ang <b>✓</b>. Tingnan ang numero at ang mensahe sa ibaba ng screen.','Pindutin ang <b>✕</b> para alisin ang force.'],'Hakbang 5: <b>15.00 sa tabi ng AI0273 lang</b>; WALANG numero sa tabi ng AT-FG1122 at ng ALM. Hakbang 6: nagiging <b>25</b> (hanggang range lang) at may mensaheng "Limited to the range written on the drawing: 0 ~ 25 %".','15.00 ay lumabas sa AI0273 lang; 99 ay naging 25.','Kung may numero pa sa ALM o sa AT-FG1122, o lumampas sa 25: FAIL, screenshot.'))
G.append(mt('MT-03','ABC-002','SELECT CIRCUIT (SI0048) at ang SIG.AB B.0671 / B.0701','Run. Lahat ng Bad Signal = OFF.',['Sa Panel, sa <b>Analog inputs / TRANSMITTERS</b>: AI0273 = <b>4.30</b> Enter; AI0433 = <b>4.60</b> Enter.','Tingnan ang dalawang wire mula sa SIG.AB junction pababa sa <b>SELECT CIRCUIT</b>. Basahin ang <b>SI0048</b>.','Sa Panel, sa grupong <b>Bad Signal (SIG.AB)</b>: pindutin ang button ng <b>B.0671</b> (nagiging FORCED BAD). Tingnan ang wire papunta sa circuit at ang SI0048.','Ibalik sa OFF.','Pindutin ang button ng <b>B.0701</b>. Tingnan ang SI0048. Ibalik sa OFF.'],'Hakbang 2: parehong wire ay <b>kulay amber (may ilaw)</b>; SI0048 = <b>4.45</b>. Hakbang 3: ang wire ng AI0273 ay <b>nagiging grey</b>; SI0048 = <b>4.60</b>; may pulang FORCED BAD sa ibabaw ng AI0273. Hakbang 4: bumabalik ang ilaw at 4.45. Hakbang 5: ang wire ng AI0433 ay grey; SI0048 = <b>4.30</b>.','Nakuha ko: wires amber / amber; 4.45; kapag B.0671 bad: wire ng AI0273 grey at 4.6; ibalik: 4.45; B.0701: 4.3.','Kung grey ang wire kahit healthy, o iba ang SI0048: FAIL, isulat ang nabasa sa bawat hakbang.'))
G.append(mt('MT-04','ABC-002','Constant "32% MIN. AIR FLOW" (kahon na "A") at ang HIGH selector na ">" sa ibaba nito','Run. Wala pang binabago.',['I-click ang kahon na <b>A</b> sa tabi ng "32% MIN. AIR FLOW".','Sa Panel: basahin ang <b>Minimum air flow setting (T/H)</b> at ang linyang "Original drawing constant ... 32 %". Basahin ang numero sa wire ng constant papunta sa ">" block.','Basahin ang <b>SI0036 TAF DEMAND</b> (sa ilalim ng ">").','Palitan ang setting ng <b>500</b> (Enter). Basahin ulit ang wire ng constant at ang SI0036.','Palitan ng <b>600</b>. Basahin ang SI0036.','Pindutin ang <b>Reset this block to default</b>.'],'Hakbang 2: setting <b>400</b>; nakasulat ang orihinal na 32 %; wire = <b>400.0</b>. Hakbang 3: <b>446.0</b> (mas malaki ang SI0021 = 446.0, kaya iyon ang dumadaan). Hakbang 4: wire = 500.0; SI0036 = <b>500.0</b>. Hakbang 5: <b>600.0</b>. Hakbang 6: bumabalik sa 400.','Nakuha ko: 400 / 446.0; 500 / 500.0; 600 / 600.0.','Kung ibang numero: FAIL. Tandaan: may nakabinbing tanong sa 32 % (Tanong 2 sa report); ang test na ito ay tungkol sa T/H setting.'))
G.append(mt('MT-05','ABC-002','Division block na ÷ (ang output ay SI0049)','Run.',['Hanapin ang ÷ block (sa itaas ng "432 / 1115 SCALE CONVERT", may SI0049 sa kanan).','I-click ang maikling wire sa <b>ilalim</b> ng ÷ (galing sa X block). Sa Panel, FORCE = <b>60</b> ✓.','I-click ang wire na papasok sa <b>itaas</b> ng ÷ (ang wire na may tatak <b>SI0042</b>). FORCE = <b>120</b> ✓.','Basahin ang <b>SI0049</b>.','Alisin ang dalawang force (✕).'],'SI0049 = <b>0.50</b> (60 / 120). Dati (v1.20.8) ay minus ang nagagawa ng block na ito.','Nakuha ko: 0.5 (a = 60, b = 120).','Kung -60 o 0.00 o iba: FAIL. Isulat ang dalawang force na inilagay at ang SI0049.'))
G.append(mt('MT-06','ABC-050','Ang "BUMPLESS" ramp block na "RAMP:1% / sec"','Run.',['Piliin ang <b>ABC-050</b> at i-click ang kahong <b>BUMPLESS</b>.','Sa Panel, basahin ang <b>Rate (signal units per sec)</b>.','Palitan ng <b>7</b> (Enter).','Pindutin ang <b>Reset</b> sa toolbar. I-click ulit ang BUMPLESS at basahin ang Rate.','Pindutin ang <b>Reset this block to default</b>. Basahin ang Rate.','Palitan ng <b>9</b>, tapos pindutin ang <b>F5</b> (refresh), piliin ulit ang ABC-050 at i-click ang BUMPLESS. Basahin ang Rate.'],'Hakbang 2: <b>1.5</b> (1 % ng 0 ~ 150 kg/cm2). Hakbang 4: <b>7</b> pa rin (hindi binura ng Reset). Hakbang 5: <b>1.5</b>. Hakbang 6: <b>9</b> pa rin pagkatapos ng F5.','Nakuha ko: 1.5, 7, 7, 1.5, 9.','Kung bumalik sa 1.5 pagkatapos ng Reset o ng F5: FAIL.'))
G.append(mt('MT-07','ABC-002','SIG.AB B.0671 at B.0701 laban sa AI0273 at AI0433','Run.',['Piliin ang <b>ABC-002</b>. Sa Panel, pindutin ang Bad Signal button ng <b>B.0671</b>.','Tingnan kung saang transmitter lumabas ang pulang <b>FORCED BAD</b>.','Ibalik sa OFF. Gawin ang pareho sa <b>B.0701</b>.'],'B.0671 = <b>AI0273</b> (kaliwa). B.0701 = <b>AI0433</b> (kanan). Batayan ay ang koneksyon ng wire, hindi ang layo.','Nakuha ko: B.0671 sa AI0273, B.0701 sa AI0433.','Kung nasa maling transmitter ang marka: FAIL, screenshot.'))
G.append(mt('MT-08','ABC-010','F(X) na may LN38 at F(X) na may LN39 (drum level compensation)','Kahit anong mode.',['Piliin ang <b>ABC-010</b> at i-click ang F(X) na may <b>LN38</b>.','Sa Panel, basahin ang linyang "Table LN38 ... 16 points".','Pindutin ang <b>Edit table</b> at basahin ang mga numero ng LX at LY (huwag palitan ang anuman).','Ihambing sa screenshot mo ng Ptrn038: LX01 = -20, LX02 = 0, LX03 = 7.60 (LY03 = 99.12) ... LX16 = 87.60 (LY16 = 77.15).','Gawin ang pareho sa F(X) na may <b>LN39</b> (Ptrn039): LY03 = 87.76 ... LY16 = 19.76.'],'16 points; ang LX / LY ay tugma sa DCS screenshots mo.','Nakuha ko sa LN38: -20 / 100, 0 / 100, 7.6 / 99.12 (16 points).','Kung may hindi tugma: FAIL, isulat ang LX at LY na hindi tugma.'))
G.append(mt('MT-09','ABC-050, ABC-051, ABC-002, ABC-001A','Mga High (HS) at Low (LS) selector na may dalawang input','Run.',['<b>ABC-050</b> (HS, output SI0228): i-click ang wire <b>SI0226</b>, FORCE = <b>70</b> ✓. I-click ang wire <b>SI0227</b>, FORCE = <b>30</b> ✓.','Tingnan ang dalawang wire malapit sa selector at ang <b>SI0228</b>.','Baligtarin: SI0226 = <b>30</b>, SI0227 = <b>70</b>. Tingnan ulit.','Alisin ang force (✕) sa dalawa.','Ulitin ang hakbang 1-4 sa: <b>ABC-051</b> HS (SI0172 at SI0171, output SI0173); <b>ABC-002</b> HS (SI0030 at SI0040, output SI0031); <b>ABC-001A</b> <b>LS</b> (SI0204 at HIC-MWLL.MV, output SI0206).'],'HS: SI0228 = <b>70</b> (ang mas malaki), at ang wire ng mas malaki ay <b>may ilaw</b> habang ang wire ng mas maliit ay <b>naka-grey</b> sa bahagi malapit sa selector. LS (ABC-001A): ang output ay ang <b>mas maliit</b> at ang mas maliit ang may ilaw.','Sa 18 selector (36 kaso) pasado lahat sa test: tama ang output at ang ilaw.','Kung pareho ang kulay ng dalawang wire, o hindi ang mas malaki (HS) / mas maliit (LS) ang output: FAIL, isulat ang sheet.'))
G.append(mt('MT-10','ABC-003B','Mga button na Wire values at Review marks','Run.',['Piliin ang <b>ABC-003B</b>. Tingnan ang mga maliliit na berdeng numero sa mga wire na walang address at ang mga amber na putol-putol na kahon.','Pindutin ang <b>Review marks</b> (off).','Pindutin ang <b>Wire values</b> (off). Pindutin ulit pareho (on).'],'On: 30 na numero sa wire na walang address (dagdag sa 31 address); 7 na amber na kahon (3 na "?" at 4 na "pin?"). Review marks off: nawawala ang mga kahon. Wire values off: nawawala ang mga numero sa wire; nananatili ang mga numero sa tabi ng address.','Nakuha ko ang mga bilang na iyon.','Kung hindi nawawala o hindi bumabalik: FAIL.'))
G.append(mt('MT-11','-','Portable EXE (Windows)','Na-download mo ang <b>logic-sim-v%s-portable.exe</b>.'%V,['I-double click ang EXE. Kung may SmartScreen: <b>More info</b> tapos <b>Run anyway</b>.','Pindutin ang <b>Analog · ABC</b> at piliin ang <b>ABC-002</b>.','Gawin ang MT-01 at MT-04.'],'Bumubukas; kapareho ng HTML; ang title ay may <b>v%s</b>.'%V,'HINDI ko pa ito na-run (na-build lang ng GitHub). NOT TESTED.','Kung hindi bumukas: isulat ang mensahe at screenshot.'))
G.append(mt('MT-12','-','APK (Android)','Na-download mo ang <b>logic-sim-v%s.apk</b>.'%V,['I-tap ang APK. Payagan ang <b>install unknown apps</b> kung hihingin.','Buksan. Pindutin ang <b>Analog · ABC</b> at piliin ang <b>ABC-002</b>.','Gawin ang MT-01.'],'Na-i-install at bumubukas; kapareho ang toolbar.','HINDI ko pa ito na-install. NOT TESTED.','Kung hindi ma-install o bumukas: isulat ang mensahe ng Android.'))
G.append('<h2>Resulta ng guide</h2>'+table(['Test','PASS / FAIL','Mga tala'],[[t,'',''] for t in ['MT-01','MT-02','MT-03','MT-04','MT-05','MT-06','MT-07','MT-08','MT-09','MT-10','MT-11','MT-12']]))
G.append('<small>Ipadala sa akin ang listahang ito (kahit larawan lang) at ang screenshot ng bawat FAIL. Hindi mo kailangang mag-code.</small>')
open('docs/LogicSim_v%s_Manual_Testing_Guide.html'%V,'w').write(page('Logic Sim v%s Manual Testing Guide'%V,''.join(G)))
print('guide ok')
