/* Who may be edited by the user? Classifies EVERY external input of every sheet and writes docs/SIGNAL-ROLES.md. usage: node tools/audit-roles.js <html> */
const {chromium}=require('/opt/node-tools/node_modules/playwright');const path=require('path'),fs=require('fs');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const p=await(await b.newContext({viewport:{width:1700,height:950}})).newPage();
await p.goto('file://'+path.resolve(process.argv[2]));await p.waitForTimeout(2500);await p.click('text=Analog · ABC >> nth=0');await p.waitForTimeout(3500);
const r=await p.evaluate(async()=>{await AN.data;const rows=[],cnt={};
 for(const sh of AN.sheets){if(/ABC-000/.test(sh.name))continue;const S=sh.S||AN.ensure(sh);
  for(const n of S.ext){const dig=!!S.nets[n].dig,link=!!(S.xlk&&S.xlk[n]);let cls;
   const seen=new Set([n]),q=[n];let pid=false;while(q.length&&seen.size<400){const x=q.shift();for(const c of(S.cns[x]||[])){if(c.k==='PID'||c.k==='PIDV')pid=true;for(const o of(c.o||[]))if(o>=0&&!seen.has(o)){seen.add(o);q.push(o)}}}
   let lk=null,ci=null;try{lk=AN.procLock(S,n)}catch(e){}try{ci=AN.cosInfo(S,n)}catch(e){}
   if(link)cls='linked from another sheet (set there)';else if(ci)cls=dig?'operator switch (COS)':'operator value (COS / SV)';else if(lk)cls='PV of a loop: simulated by the process model';else if(pid)cls=dig?'switch / mode / status that reaches a controller':'REVIEW: analog that reaches a controller and is still editable';else cls=dig?'switch / status / DITL signal':'field measurement or disturbance, not tied to a controller';
   const key=(dig?'digital: ':'analog: ')+cls;cnt[key]=(cnt[key]||0)+1;
   if(!dig&&!link){let t=(S.lab[n]&&S.lab[n].t)||'',d='';try{d=AN.nm(S,n)}catch(e){}try{const a=AN.adesFind(sh,t);if(a&&a.rec)d=[a.rec.tag,a.rec.d].filter(Boolean).join(' · ')}catch(e){}rows.push([sh.name,t||('wire '+n),d,cls])}}}
 return{rows,cnt}});
const L=['# SIGNAL ROLES - who may be edited (generated by tools/audit-roles.js, v1.18.x)','','Why: in a real plant the operator changes the SV, the manual values and the switches; the PV and the feedbacks are the plant answering. The simulator has no plant, so every field signal is an input. This table classifies EVERY external input of the 51 sheets so that the right method can be chosen (docs/SIMULATION-METHOD.md).','','## Counts','| Role | Inputs |','|---|---|'];
for(const k of Object.keys(r.cnt).sort())L.push('| '+k+' | '+r.cnt[k]+' |');
L.push('','## Analog inputs (not linked from another sheet): role of each','| Sheet | Wire | Description | Role |','|---|---|---|---|');
for(const x of r.rows.sort((a,b)=>a[3]<b[3]?-1:a[3]>b[3]?1:a[0]<b[0]?-1:1))L.push('| '+x.map(s=>String(s).replace(/\|/g,'/')).join(' | ')+' |');
fs.writeFileSync('docs/SIGNAL-ROLES.md',L.join('\n')+'\n');console.log(JSON.stringify(r.cnt,null,1));await b.close()})();
