/* Wiring suspects: wires that carry a value INTO a block but have NO source in the logic (the engine treats them as an input that the user must set), without a tag / address / circle that explains it. Writes docs/WIRING-SUSPECTS.md for the user to compare with the drawings.
   usage: node tools/audit-wiring.js <html> */
const {load,build}=require('./lib.js');const fs=require('fs');const {E,rows}=load(process.argv[2]);const A=[],B=[];let nA=0,nB=0;
for(const r of rows){if(/ABC-000/.test(r.name))continue;const S=build(E,r);
 for(const n of S.ext){if(S.lab[n])continue;const net=S.nets[n],cs=S.cns[n]||[];if(!cs.length)continue;
  const pins=[];for(const b of S.blk)for(const p of b.pins||[])if(p.n===n)pins.push({b,p});
  const cnt=new Map();for(const i of net.segs){const s=S.seg[i];for(const [x,y] of [[s.x1,s.y1],[s.x2,s.y2]]){const k=x.toFixed(1)+','+y.toFixed(1);cnt.set(k,(cnt.get(k)||0)+1)}}
  const ends=[...cnt.entries()].filter(([k,c])=>c===1).map(([k])=>k.split(',').map(Number));
  let txt='',best=1e9;for(const [x,y] of ends)for(const t of S.tx){const d=Math.hypot(t.x-x,t.y-y);if(d<best){best=d;txt=t.t.trim()}}
  const circ=(S.conn||[]).concat(S.xc||[]).some(c=>ends.some(([x,y])=>Math.hypot(c.x-x,c.y-y)<=c.r+1.5));
  const onlyIn=pins.length>=2&&pins.every(q=>q.p.role==='in');
  const desc=r.name+' | net '+n+' | '+(net.dig?'digital':'analog')+' | consumers '+cs.map(c=>c.k+'#'+c.id+'@'+Math.round(c.cx)+','+Math.round(c.cy)).join(', ')+' | free ends '+ends.map(e=>Math.round(e[0])+','+Math.round(e[1])).join(' ; ')+' | nearest text "'+txt.slice(0,30)+'" ('+best.toFixed(1)+')';
  if(onlyIn&&!circ){A.push(desc);nA++}else if(!net.dig&&!circ&&best>2.5){B.push(desc);nB++}}}
const L=['# WIRING SUSPECTS (generated by tools/audit-wiring.js, WIP after v1.18.0)','','A wire that carries a value into a block but has no source in the logic is treated as an INPUT that the user must set. That is right for a tag, an address or a circle; it is wrong when the drawing really connects it to another wire or block output and the reader missed the connection (found so far: the SIG.AB branch of ABC-002, the arrow into a wire of ABC-003E ...). This list is what is left: compare with the drawings (coordinates are drawing units, as in the status line).','',
'## A. Wires that join only INPUT pins (no output on the wire) - '+nA,'| Sheet | Net | Kind | Consumers (block @ x,y) | Free ends | Nearest text |','|---|---|---|---|---|---|'];
for(const d of A){const q=d.split(' | ');L.push('| '+q.join(' | ')+' |')}
L.push('','## B. Analog wires with a free end that has NO text, tag or circle within 2.5 units - '+nB,'| Sheet | Net | Kind | Consumers (block @ x,y) | Free ends | Nearest text |','|---|---|---|---|---|---|');
for(const d of B){const q=d.split(' | ');L.push('| '+q.join(' | ')+' |')}
fs.writeFileSync('docs/WIRING-SUSPECTS.md',L.join('\n')+'\n');console.log('A (only input pins):',nA,'| B (analog, free end without text / circle):',nB);
