/* Who may be edited by the user? Classifies EVERY point at the field / operator side of every sheet (transmitters = AI blocks, SIG.AB flags, external input wires) with the description of the IO list / memory list, and writes docs/SIGNAL-ROLES.md.
   usage: node tools/audit-roles.js <html> */
const {chromium}=require('/opt/node-tools/node_modules/playwright');const path=require('path'),fs=require('fs');
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const p=await(await b.newContext({viewport:{width:1700,height:950}})).newPage();
await p.goto('file://'+path.resolve(process.argv[2]));await p.waitForTimeout(2500);await p.click('text=Analog · ABC >> nth=0');await p.waitForTimeout(3500);
const r=await p.evaluate(async()=>{await AN.data;const rows=[],cnt={};
 const desc=(sh,t)=>{try{const a=AN.adesFind(sh,t);if(a&&a.rec){const q=a.rec;return[q.tag,q.d,q.t,(q.lo!=null||q.hi!=null)?q.lo+' ~ '+q.hi+' '+(q.u||''):''].filter(Boolean).join(' · ')}}catch(e){}return''};
 for(const sh of AN.sheets){if(/ABC-000/.test(sh.name))continue;const S=sh.S||AN.ensure(sh);
  const add=(kind,dig,label,d,role,det)=>{const key=(dig?'digital':'analog')+' · '+role;cnt[key]=(cnt[key]||0)+1;rows.push([sh.name,dig?'D':'A',kind,label,d,role,det||''])};
  for(const b of S.blk){if(b.k!=='AI'&&b.k!=='SIGAB')continue;const o=b.pins.find(q=>q.role==='out');if(!o)continue;const n=o.n,lab=(S.lab[n]&&S.lab[n].t)||b.tagAI||(b.txt||[]).join(' ')||('wire '+n);
   if(b.k==='SIGAB'){add('SIG.AB flag',true,lab,desc(sh,lab),'operator switch (signal bad flag)');continue}
   let role,pb=null;try{pb=AN.procAI(S,b.id)}catch(e){}
   let det='';if(b.fb)role='feedback: follows the position of its valve / actuator';else if(pb){role='plant-driven (read only; F = simulate)';det='measurement of '+((pb.txt||[])[1]||pb.k)}else role='free transmitter: operator edits it (no modelled loop uses it)';
   add('transmitter AI',false,lab,desc(sh,lab)+(b.rng?' | range '+b.rng.lo+' ~ '+b.rng.hi+' '+(b.rng.u||''):''),role,det)}
  for(const n of S.ext){const dig=!!S.nets[n].dig,link=!!(S.xlk&&S.xlk[n]);let lab='';try{lab=AN.nm(S,n)}catch(e){}const t=(S.lab[n]&&S.lab[n].t)||'';let ci=null,lk=null;try{ci=AN.cosInfo(S,n)}catch(e){}try{lk=AN.procLock(S,n)}catch(e){}
   let role,det='';if(link)role='linked from another sheet (set there)';else if(ci)role=dig?'operator switch (COS)':(ci.role==='SV'?'operator SV (COS)':'operator value (COS)');else if(lk){role='plant-driven (read only; F = simulate)';det='PV input of '+((lk.txt||[])[1]||lk.k)}else if(/\.(MAN|LOC|REM)$/i.test(t))role='operator mode input (A / M / CAS from the logic)';else if(/^(DITL|S\d\s+)?[A-Z]\.\d{4}$/.test(t)||/^[BIM]\.\d{4}/.test(t))role=dig?'switch / status / DITL signal (operator)':'other analog input (operator)';else role=dig?'switch / status / DITL signal (operator)':'other analog input (operator)';
   add('input wire',dig,t||lab,desc(sh,t),role,det)}}
 return{rows,cnt}});
const L=['# SIGNAL ROLES - who may be edited (generated by tools/audit-roles.js, v1.18.x WIP)','','Why: in a real plant the operator changes the SV, the manual values and the switches; the PV and the feedbacks are the plant answering. The simulator has no plant, so every field point is an input unless the plant model drives it. This table classifies EVERY field / operator side point of the 51 sheets (transmitters = AI blocks, SIG.AB flags, external input wires) with the description of the IO list / memory list (the files the user gave).','','## Counts','| Role | Points |','|---|---|'];
for(const k of Object.keys(r.cnt).sort())L.push('| '+k+' | '+r.cnt[k]+' |');
L.push('| **Total** | **'+r.rows.length+'** |','','## Every point','| Sheet | A/D | Kind | Address / wire | IO list / memory list | Role | Detail |','|---|---|---|---|---|---|---|');
for(const x of r.rows.sort((a,b)=>a[5]<b[5]?-1:a[5]>b[5]?1:a[0]<b[0]?-1:a[0]>b[0]?1:0))L.push('| '+x.map(s=>String(s).replace(/\|/g,'/')).join(' | ')+' |');
fs.writeFileSync('docs/SIGNAL-ROLES.md',L.join('\n')+'\n');console.log(JSON.stringify(r.cnt,null,1));console.log('total',r.rows.length);await b.close()})();
