/* Parameters the reader took from texts, compared with the texts again: comparator set points (">= 83.3%", "< 18%", "<= PICMS1006.MLD"), timer times ("2s", "5 SEC", "300s"), LAG time constants.  usage: node tools/audit-params.js file.html */
const {load,build}=require('./lib.js');const {E,rows}=load(process.argv[2]);const out=[];let nc=0,nt=0,nl=0;
for(const r of rows){if(/ABC-000/.test(r.name))continue;const S=build(E,r);
 for(const b of S.blk){const P=b.p||{};const near=(re,rad)=>S.tx.filter(t=>Math.hypot(t.x-b.cx,t.y-b.cy)<=rad&&re.test(t.t.replace(/%%%/g,'%').trim())).sort((u,v)=>Math.hypot(u.x-b.cx,u.y-b.cy)-Math.hypot(v.x-b.cx,v.y-b.cy));
  if(['HC','LC','HLC'].includes(b.k)){nc++;const c=near(/^[<>≤≥]\s*=?\s*(-?\d+(?:\.\d+)?)/,16);if(!c.length){if(P.ref==null&&!P.found)out.push([r.name,b.k+'#'+b.id,'@'+Math.round(b.cx)+','+Math.round(b.cy),'no ">/<" text within 16; sim uses '+(P.op||'')+' '+P.sp].join(' | '));continue}
   const m=c[0].t.replace(/%%%/g,'%').trim().match(/^([<>≤≥])\s*(=)?\s*(-?\d+(?:\.\d+)?)/);const sp=+m[3];if(P.ref==null&&Math.abs((P.sp||0)-sp)>1e-6)out.push([r.name,b.k+'#'+b.id,'@'+Math.round(b.cx)+','+Math.round(b.cy),'text "'+c[0].t.trim()+'" but sim set point '+P.sp+' ('+(P.op||'')+')'].join(' | '))}
  if(['TON','TOF','TPS'].includes(b.k)){nt++;const c=near(/^\d+(?:\.\d+)?\s*(?:s|sec|min)\b/i,16);if(c.length){const m=c[0].t.trim().match(/^(\d+(?:\.\d+)?)\s*(s|sec|min)/i);const sec=+m[1]*(/min/i.test(m[2])?60:1);if(P.sec&&Math.abs(P.sec-sec)>1e-6)out.push([r.name,b.k+'#'+b.id,'@'+Math.round(b.cx)+','+Math.round(b.cy),'text "'+c[0].t.trim()+'" but sim time '+P.sec+' s'].join(' | '))}else out.push([r.name,b.k+'#'+b.id,'@'+Math.round(b.cx)+','+Math.round(b.cy),'no time text within 16; sim '+P.sec+' s'].join(' | '))}
  if(b.k==='LAG'){nl++;const c=near(/^\d+(?:\.\d+)?\s*(?:sec|s|min)/i,14);if(!c.length)out.push([r.name,'LAG#'+b.id,'@'+Math.round(b.cx)+','+Math.round(b.cy),'no time text within 14; sim uses default '+P.tau+' s'].join(' | '))}}}
console.log('comparators',nc,'timers',nt,'LAG',nl,'| lines to look at:',out.length);out.forEach(x=>console.log(x));
