/* Writes docs/PLANT-MODEL.md: for EVERY PID / PIDV of the 51 sheets, which input of the deviation block is the PV (by the PV / SV text of the drawing), how the plant model drives it, and the estimated gain / time constant / dead time.  usage: node tools/list-plant.js <html> */
const {load,build}=require('./lib.js');const fs=require('fs');const {E,rows}=load(process.argv[2]);const L=[],cnt={};
L.push('# PLANT MODEL - every controller of every sheet (generated by tools/list-plant.js, v1.18.x WIP)','',
'How to read: the **PV pin** is the input of the deviation (DEV) block that the drawing marks "PV" (text beside the pin; where there is no text, the action decides: reverse -> minus pin, direct -> plus pin). The **plant model** answers at the INPUT of the sheet:',
'- **transmitter**: the plant writes the AI block(s) of the measurement; the blocks of the sheet between the transmitter and the PID (selection, average, square root, compensation, deviation alarm) run as drawn. Only the transmitters that really move the PV are driven (found by probing); compensation inputs (pressure, temperature) start at the middle of their range.',
'- **input**: the PV of the PID is an input wire of the sheet; the plant writes that wire (read only for the user).',
'- **pin**: the PV is a calculation of the sheet (several measurements, switches, constants) and no transmitter moves it: the plant writes the PV wire itself (a hold on that wire; the user FORCE wins).',
'- **shared**: another controller of the same sheet measures the SAME variable; one variable has one plant model, on the first controller.',
'- **none**: the PV is calculated from other controllers (cascade / ratio / sum): there is no field signal to simulate.','',
'**K, T, L are ESTIMATED from the tuning of the controller, not measured** (a tuned loop: Ti ~ T, Kp x K ~ 0.6, dead time from Td, otherwise T/12). They can be changed in the controller panel; the real values need a step test on the plant.','',
'| Sheet | Controller | Action | PV pin (by drawing text / by rule) | SV pin | Mode | Driven transmitters | Kp | Ti (s) | Td (s) | K | T (s) | L (s) | Loop type |','|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for(const r of rows){if(/ABC-000/.test(r.name))continue;const S=build(E,r);S.procs=E.anProcList(S);
 for(const b of S.blk){if(b.k!=='PID'&&b.k!=='PIDV')continue;const pn=E.anPins(S,b),tag=(b.txt||[])[1]||b.k,nmn=n=>{const l=S.lab[n];return l&&l.t?l.t:'#'+n};
  if(!pn){L.push('| '+r.name+' | '+tag+' | - | no deviation block | | none | | | | | | | | |');cnt.none=(cnt.none||0)+1;continue}
  const pr=b.proc,mode=pr?pr.mode:'none',ai=pr&&pr.ai?pr.ai.map(id=>{const a=S.blk.find(x=>x.id===id);return (a&&a.tagAI)||('AI#'+id)}).join(', '):'';cnt[mode]=(cnt[mode]||0)+1;
  L.push('| '+[r.name,tag+(b.k==='PIDV'?' (PIDV)':''),b.p.act<0?'reverse':'direct',nmn(pn.pv)+' ('+(pn.byLabel?'drawing text':'rule')+')',nmn(pn.sv),mode+(pr&&pr.fell?' (fell back)':'')+(pr&&pr.mode==='shared'?' of '+pr.of:''),ai,(+b.p.kp).toFixed(2),b.p.ti,b.p.td,pr&&pr.mode!=='shared'?pr.K:'',pr&&pr.mode!=='shared'?pr.T:'',pr&&pr.mode!=='shared'?pr.L:'',b.p.lt||'general'].join(' | ')+' |')}}
L.splice(L.indexOf('**K, T, L'),0,'**Count by mode:** '+Object.entries(cnt).map(([k,v])=>k+' '+v).join(' · ')+'.','');
fs.writeFileSync('docs/PLANT-MODEL.md',L.join('\n')+'\n');console.log(JSON.stringify(cnt));
