/* v1.16.1 WIP: the PID / MAN / SUMA faceplate values the user wrote from the DCS (FILE data: tools/data/dcs-form2-filled.json) replace the default tuning:
   PID / PIDV: Kp = 100 / P (P is a percent band), Ti = I, Td = D, output limits ML ~ MH, SV range SL ~ SH (span = SH - SL), the other parameters are kept in the block (dMVH DTI TF GAP BND CUT DH PHONDT PLONDT: recorded, not used yet);
   MAN: value range SL ~ SH cut by the MV limits (ML / MH in % of the range); SUMA: RSTS, K, DT, TF, CUT recorded. Match by station + MNO (the number of the S1-MDLnnn address on the drawing). */
module.exports=(rep)=>{
rep(String.raw`function anDefaults(S){if(typeof AN_DEF==='undefined')return;`,String.raw`function anFace(S){const F=AN_DEF.FACE;if(!F)return;
 for(const b of S.blk){const k=b.k==='MAN'?'MAN':(b.k==='PID'||b.k==='PIDV')?'PID':b.k==='SUMA'?'SUMA':null;if(!k)continue;const m=(b.txt||[]).map(t=>/^S(\d)-MDL(\d+)$/i.exec(t)).find(Boolean);if(!m)continue;const stn=100+ +m[1],mno=+m[2],e=(F[k]||[]).find(q=>q.stn===stn&&q.mno===mno);if(!e)continue;const P=b.p;b.face=e;
  if(k==='PID'){if(e.P>0)P.kp=+(100/e.P).toFixed(6);P.ti=e.I;P.td=e.D;P.lo=e.ML;P.hi=e.MH;const sp=e.SH-e.SL;if(sp>0){P.span=sp;P.rlo=e.SL;P.rhi=e.SH}if(e.unit)P.unit=e.unit;P.ph=e.PH;P.pl=e.PL;P.dmvh=e.dMVH;P.dti=e.DTI;P.tf=e.TF;P.gap=e.GAP;P.bnd=e.BND;P.cut=e.CUT;P.dh=e.DH;P.phondt=e.PHONDT;P.plondt=e.PLONDT}
  else if(k==='MAN'){const sp=e.SH-e.SL;if(sp>0){P.lo=e.SL+e.ML/100*sp;P.hi=e.SL+e.MH/100*sp;P.rlo=e.SL;P.rhi=e.SH}if(e.unit)P.u=e.unit;P.ph=e.PH;P.pl=e.PL;P.dh=e.DH;P.dt=e.DT;P.tf=e.TF;P.fsc=e.FSC;P.cut=e.CUT;P.phondt=e.PHONDT;P.plondt=e.PLONDT}
  else{P.ph=e.PH;P.pl=e.PL;P.rsts=e.RSTS;P.kk=e.K;P.dt=e.DT;P.tf=e.TF;P.cut=e.CUT;P.phondt=e.PHONDT;P.plondt=e.PLONDT;P.sumUnit=e['SUM unit']}}}
function anDefaults(S){if(typeof AN_DEF==='undefined')return;anFace(S);`);
/* panel text of the PID */
rep(String.raw` comes from the drawing. Kp / Ti / Td are DEFAULT values (the real tuning is in the DCS database, not in the drawings): edit them here. While the T`,
String.raw` comes from the drawing. '+(b.face?'Kp / Ti / Td, the output limits and the SV range are the VALUES OF THE DCS FACEPLATE (user file, 2026-10-08, MNO '+b.face.mno+'): P = '+b.face.P+' % band (Kp = 100 / P), I = '+b.face.I+' s, D = '+b.face.D+' s, MV limits '+b.face.ML+' ~ '+b.face.MH+' %, SV range '+b.face.SL+' ~ '+b.face.SH+' '+(b.face.unit||'')+'. Recorded, not used yet by the simulator: dMVH '+b.face.dMVH+' %, DTI '+b.face.DTI+' s, TF '+b.face.TF+' s, GAP '+b.face.GAP+', BND '+b.face.BND+', CUT '+b.face.CUT+', DH '+b.face.DH+', PHONDT '+b.face.PHONDT+', PLONDT '+b.face.PLONDT+'. Edit them here. ':'Kp / Ti / Td are DEFAULT values (the real tuning is in the DCS database, not in the drawings): edit them here. ')+'While the T`);
rep(String.raw`else if(b.k==='MAN'){pr('lo','Low limit');pr('hi','High limit')}`,String.raw`else if(b.k==='MAN'){pr('lo','Low limit');pr('hi','High limit');if(b.face)d.append(h$('small',{txt:'From the DCS faceplate (MNO '+b.face.mno+'): value range '+b.face.SL+' ~ '+b.face.SH+' '+(b.face.unit||'')+', MV limits '+b.face.ML+' ~ '+b.face.MH+' % of the range (the limits above). Recorded, not used yet: DH '+b.face.DH+', DT '+b.face.DT+' s, TF '+b.face.TF+' s, FSC '+b.face.FSC+' min, CUT '+b.face.CUT+', PHONDT '+b.face.PHONDT+', PLONDT '+b.face.PLONDT+'.'}))}`);
};
