/* Group A (LINEAR FX): no silent pass-through, no silent clamp.
   anFXs(P,x) -> {y,st}. st: 'OK' | 'NOTABLE' (no table or no points: y = x is only a placeholder, the block is NEEDS REVIEW) | 'OUT' (x outside the domain of the table: the end value is held, the block is NEEDS REVIEW) | 'NAN' (input not a number). A table chosen with a warning (lnWarn: station fallback) is NEEDS REVIEW too. The status is stored in the block state (S.rt.st[id].fxs) and shown in the block panel and in the Health table. The table points are in the units of the table (xu / yu of the LINEAR file); the table domain already includes its own extension beyond the range (for % tables -20 .. 120). */
module.exports=(rep)=>{
rep(`function anFX(P,x){const ln=P.ln,t=((typeof window!=='undefined'&&window.ANLN)||{})[ln]||(P.tbl&&(P.tbl.p2||P.tbl.pts));if(!t||!t.length)return x;if(x<=t[0][0])return t[0][1];`,
`function anFXs(P,x){const ln=P.ln,t=((typeof window!=='undefined'&&window.ANLN)||{})[ln]||(P.tbl&&(P.tbl.p2||P.tbl.pts));if(!t||!t.length)return{y:x,st:'NOTABLE'};if(!(x===x))return{y:x,st:'NAN'};const w=P.lnWarn&&!(typeof window!=='undefined'&&window.ANLN&&window.ANLN[ln])?'WARN':'OK';if(x<t[0][0])return{y:t[0][1],st:'OUT'};if(x>t[t.length-1][0])return{y:t[t.length-1][1],st:'OUT'};return{y:anFX(P,x),st:w}}
function anFX(P,x){const ln=P.ln,t=((typeof window!=='undefined'&&window.ANLN)||{})[ln]||(P.tbl&&(P.tbl.p2||P.tbl.pts));if(!t||!t.length)return x;if(x<=t[0][0])return t[0][1];`);
rep(`case 'FX':out(anFX(P,rd(b.i[0])));break;`,`case 'FX':{const r=anFXs(P,rd(b.i[0]));s.fxs=r.st;out(r.y);break}`);
/* export for the tests */
rep(`anCompile,anInit,anFX,anStep,`,`anCompile,anInit,anFX,anFXs,anStep,`);
/* panel: red NEEDS REVIEW line */
rep(`if(P.lnWarn)d.append(h$('small',{style:'color:#ffb24a',txt:'⚠ '+P.lnWarn}));`,`if(P.lnWarn)d.append(h$('small',{style:'color:#ffb24a',txt:'⚠ '+P.lnWarn}));
   {const fs_=(cs().S.rt.st[b.id]||{}).fxs,why=fs_==='NOTABLE'?'no table: the output is only a placeholder (y = x), it is NOT a converted value':fs_==='OUT'?'the input is outside the domain of the table: the end value of the table is held':fs_==='NAN'?'the input is not a number':P.lnWarn?'the table was chosen with a warning (see above)':'';if(why)d.append(h$('div',{style:'color:#ff6b6b;font-weight:bold;margin:3px 0',txt:'NEEDS REVIEW: '+why}))}`);
/* Health table: one more column */
rep(`['Sheet','Blocks','External inputs','Unknown shapes','Pin issues']`,`['Sheet','Blocks','External inputs','Unknown shapes','Pin issues','LINEAR review']`);
rep(`h$('td',{cls:o.h.issues.length?'bad':'',txt:o.h.issues.length}))}`,`h$('td',{cls:o.h.issues.length?'bad':'',txt:o.h.issues.length}),(()=>{const n=o.sh.S.blk.filter(q=>q.k==='FX'&&(!(q.p.tbl&&(q.p.tbl.p2||q.p.tbl.pts))&&!(window.ANLN&&window.ANLN[q.p.ln])||q.p.lnWarn)).length;return h$('td',{cls:n?'bad':'',title:'FX blocks without a table or with a table chosen by a warning = NEEDS REVIEW',txt:n})})())}`);
/* Group D: a RATE / ramp with no rate (missing or 0) and no own limit inputs must not silently become an instant step: flagged s.rev='NO RATE' (value unchanged: pass-through), counted in the Health column */
rep(`const fx=b.up===undefined,ru=fx?P.rate:rd(b.up),rd_=fx?P.rate:rd(b.dn),d=x-s.y;`,`const fx=b.up===undefined,ru=fx?P.rate:rd(b.up),rd_=fx?P.rate:rd(b.dn),d=x-s.y;s.rev=fx&&!(P.rate>0)?'NO RATE':0;`);
rep(`'LINEAR review']`,`'LINEAR / RATE review']`);
rep(`q.k==='FX'&&(!(q.p.tbl&&(q.p.tbl.p2||q.p.tbl.pts))&&!(window.ANLN&&window.ANLN[q.p.ln])||q.p.lnWarn)).length;`,`(q.k==='FX'&&(!(q.p.tbl&&(q.p.tbl.p2||q.p.tbl.pts))&&!(window.ANLN&&window.ANLN[q.p.ln])||q.p.lnWarn))||((q.k==='RATE'||q.k==='RAMPB')&&q.main!==undefined&&q.up===undefined&&!(q.p.rate>0))).length;`);
/* RATE / RAMPB written in % (of the signal span): the rate is converted to ENGINEERING UNITS with the span of the signal that enters the block (anInit: nearest source found upstream through analog nets - AI range, FX table output range, MAN range, PID output span). Unresolved span: the old behaviour (span 100) stays and the block is marked P.spanUnres (NEEDS REVIEW). A rate written as an absolute engineering-unit value (T / Sec, kg/cm2 / min, "2.7T / HR") is used as written. */
rep(`:1;const mp=ins.find(p=>p.side==='L')||ins[0],bp=`,`:1;P.pct=!!t&&/%/.test(t);P.rtxt=t||'';const mp=ins.find(p=>p.side==='L')||ins[0],bp=`);
rep(`P.rate=t&&anNum(t.t)>0?anNum(t.t)/(/\\/\\s*min/i.test(t.t)?60:/\\/\\s*(hr|h)\\b/i.test(t.t)?3600:1):0;if((b.txt||[]).some(q=>q.trim()==='V')){`,`P.rate=t&&anNum(t.t)>0?anNum(t.t)/(/\\/\\s*min/i.test(t.t)?60:/\\/\\s*(hr|h)\\b/i.test(t.t)?3600:1):0;P.pct=!!t&&/%/.test(t.t);P.rtxt=t?t.t.trim():'';if((b.txt||[]).some(q=>q.trim()==='V')){{const at=near(b.cx,b.cy,70,q=>/\\d\\s*T\\s*\\/\\s*(hr|h)\\b/i.test(q.t.trim()))[0];if(at){const am=/(\\d+(?:\\.\\d+)?)\\s*T\\s*\\/\\s*(?:hr|h)\\b/i.exec(at.t);P.absHr=+am[1];P.rtxt=at.t.trim()}}`);
rep(`P.rate=+m[1]/3600;P.hr=+m[1]}else P.rate=0}b.main=an[0]`,`P.rate=+m[1]/3600;P.hr=+m[1];P.pct=true;if(P.absHr>0){P.rate=P.absHr/3600;P.pct=false}}else P.rate=0}b.main=an[0]`);
rep(` for(const n of S.ext){rt.ext[n]=S.nets[n].dig?0:0}`,` /* span of the signal that enters a RATE / RAMPB written in % (nearest source upstream, analog nets only) */
 for(const b of S.blk)if((b.k==='RATE'||b.k==='RAMPB')&&b.p.pct&&b.main!==undefined&&b.main>=0&&b.up===undefined){
  const blkOf=d=>d.k&&d.id!==undefined&&d.i===undefined?S.blk.find(z=>z.id===d.id):d;
  const srcOf=bl=>{if(bl.k==='AI'&&bl.rng&&bl.rng.hi>bl.rng.lo)return{sp:bl.rng.hi-bl.rng.lo,t:'AI#'+bl.id+' '+bl.rng.lo+'~'+bl.rng.hi+' '+(bl.rng.u||'')};
   if(bl.k==='FX'&&bl.p.tbl&&bl.p.tbl.yr&&bl.p.tbl.yr[1]>bl.p.tbl.yr[0])return{sp:bl.p.tbl.yr[1]-bl.p.tbl.yr[0],t:'FX#'+bl.id+' '+bl.p.ln+' output '+bl.p.tbl.yr[0]+'~'+bl.p.tbl.yr[1]+' '+(bl.p.tbl.yu||'')};
   if(bl.k==='MAN'&&bl.p&&bl.p.rhi>bl.p.rlo)return{sp:bl.p.rhi-bl.p.rlo,t:'MAN#'+bl.id+' '+bl.p.rlo+'~'+bl.p.rhi};
   if((bl.k==='PID'||bl.k==='PIDV')&&bl.p&&bl.p.hi>bl.p.lo)return{sp:bl.p.hi-bl.p.lo,t:'PID#'+bl.id+' output '+bl.p.lo+'~'+bl.p.hi};return null};
  /* upstream: level by level; the first level with sources must agree on one span, otherwise it is ambiguous */
  let U=null,Uamb=null;{const seen=new Set([b.main]);let lvl=[b.main];for(let g=0;lvl.length&&g<40&&!U&&!Uamb;g++){const found=[],nx=[];for(const n of lvl)for(const d of S.drv[n]||[]){const bl=blkOf(d);if(!bl)continue;const sc=srcOf(bl);if(sc){found.push(sc);continue}for(const m of bl.i||[])if(m>=0&&!seen.has(m)&&!S.nets[m].dig){seen.add(m);nx.push(m)}}
    if(found.length){const u=[...new Set(found.map(f=>f.sp))];if(u.length===1)U={sp:u[0],t:found.map(f=>f.t).join(' + ')};else Uamb=found.map(f=>f.t).join(' vs ')}lvl=nx}}
  /* downstream: a controller whose input chain contains the output of this block and that has its own drawn range ("0.0 ~ 200.0 T/H") */
  let D=null;{const tg=b.o[0];for(const c of S.blk)if((c.k==='PID'||c.k==='PIDV')&&c.p&&c.p.rhi>c.p.rlo&&c.i&&c.i.length){const seen=new Set(),q=c.i.slice();let hit=false;for(let g=0;q.length&&g<200&&!hit;g++){const n=q.shift();if(n===tg){hit=true;break}if(seen.has(n)||n<0)continue;seen.add(n);for(const d of S.drv[n]||[]){const bl=blkOf(d);if(!bl||bl.k==='PID'||bl.k==='PIDV')continue;for(const m of bl.i||[])if(!S.nets[m].dig)q.push(m)}}
    if(hit){D={sp:c.p.rhi-c.p.rlo,t:'PID#'+c.id+' drawn range '+c.p.rlo+'~'+c.p.rhi+' '+(c.p.unit||'')};break}}}
  let pick=null,why='';
  if(D){pick=D;why='downstream '+D.t+(U?(U.sp===D.sp?' (agrees with upstream '+U.t+')':' (upstream source differs: '+U.t+' - not used)'):'')}
  else if(U){pick=U;why='upstream '+U.t}
  else if(Uamb)why='AMBIGUOUS upstream: '+Uamb;
  if(pick){b.p.span=pick.sp;b.p.spanSrc=why;b.p.ratePct=b.p.rate;b.p.rate=b.p.rate*pick.sp/100}else{b.p.spanUnres=true;b.p.span=100;b.p.spanSrc=(why||'no range source found')+' -> old behaviour kept (span 100)'}}
 for(const n of S.ext){rt.ext[n]=S.nets[n].dig?0:0}`);
/* ABC-002 minimum air flow (finding 11, user decision 2026-10-10): the drawing constant "32% MIN. AIR FLOW" stays as the original value (P.val, P.orig); the user edits the minimum air flow in T/H (default 400 T/H). Signal to the high selector (%) = T/H x P.k; P.k (% per T/H) starts at 32 / 400 = 0.08 so that the default reproduces the drawing value; it is shown and editable, and NEEDS REVIEW (the drawing's own SCALE CONVERT 35 / 1115 is a different factor). */
rep(`   case 'CONST':out(P.val);break;`,`   case 'CONST':out(P.mt?P.th*P.k:P.val);break;`);
rep(` for(const n of S.ext){rt.ext[n]=S.nets[n].dig?0:0}`,` for(const b of S.blk)if(b.k==='CONST'&&P_isMinAir(S,b)&&b.p.val>0){const P=b.p;if(P.orig==null)P.orig=P.val;if(P.th==null)P.th=400;if(P.k==null)P.k=P.orig/400;P.mt=1}
 for(const n of S.ext){rt.ext[n]=S.nets[n].dig?0:0}`);
rep(`function anFXs(P,x){`,`function P_isMinAir(S,b){return (S.tx||[]).some(t=>/MIN\\.?\\s*AIR\\s*FLOW/i.test(t.t)&&Math.hypot(t.x-b.cx,t.y-b.cy)<=60)&&(S.tx||[]).some(t=>/^32\\s*%/.test(t.t.trim())&&Math.hypot(t.x-b.cx,t.y-b.cy)<=40)}
function anFXs(P,x){`);
rep(` else if(b.k==='CONST')pr('val','Value');`,` else if(b.k==='CONST'&&P.mt){d.append(h$('div',{cls:'r'},[h$('span',{cls:'n',style:'font-weight:bold',txt:'Minimum air flow setting (T/H) - editable'}),num(P.th,x=>pSet(sh,b,'th',x),5)]),h$('div',{cls:'r'},[h$('span',{cls:'n',txt:'Conversion to the % signal (% per T/H)'}),num(P.k,x=>pSet(sh,b,'k',x),.001)]),h$('small',{style:'color:#ffb24a',txt:'NEEDS REVIEW: the conversion starts at 32 % / 400 T/H = 0.08 so that the default equals the drawing constant. It is not written on the drawing (SCALE CONVERT 35 / 1115 is a different factor). Edit it if the real relation is known.'}),h$('div',{cls:'r'},[h$('span',{cls:'n',txt:'Original drawing constant (kept for comparison)'}),h$('b',{txt:P.orig+' %'})]),h$('div',{cls:'r'},[h$('span',{cls:'n',txt:'Signal to the high selector now'}),h$('b',{txt:(Math.round(P.th*P.k*1000)/1000)+' %  (= '+P.th+' T/H x '+P.k+')'})]),h$('button',{txt:'Back to the drawing value (32 % = 400 T/H)',onclick:()=>{pSet(sh,b,'th',400);pSet(sh,b,'k',P.orig/400)}}))}
 else if(b.k==='CONST')pr('val','Value');`);
/* SIG.AB: user-controlled BAD SIGNAL (simulation only, OFF by default, nothing is written to a DCS). The SIG.AB flag of a transmitter is a manual input: the user forces it ON (FORCED BAD) or OFF per transmitter; the existing wiring / logic (SEL, T switches, comparators) responds. No hold-last behaviour is added. A zero reading never sets the flag. v1.20.8: clear labels in the panel, a FORCED BAD mark on the diagram, the same control in the transmitter inspector. */
rep(`bt=h$('button',{txt:'0'});bt.classList.add('wr');bt.onclick=()=>{st.val=st.val?0:1;(sv(sh).ai=sv(sh).ai||{})[b.id]=st.val;anSave();settle()};`,`bt=h$('button',{txt:'Bad Signal: OFF',title:'Simulation only. OFF (default) = the transmitter is normal. ON = FORCED BAD: the SIG.AB flag is set, the drawn logic reacts.'});bt.classList.add('wr');bt.onclick=()=>{st.val=st.val?0:1;(sv(sh).ai=sv(sh).ai||{})[b.id]=st.val;anSave();settle()};`);
rep(`PU.push(()=>{bt.textContent=st.val?'1 · ON':'0 · OFF';bt.classList.toggle('on',!!st.val)})});`,`PU.push(()=>{bt.textContent=st.val?'FORCED BAD (ON)':'Bad Signal: OFF';bt.classList.toggle('on',!!st.val)})});`);
rep(`grp('Digital inputs','Signal bad flags (SIG.AB)')`,`grp('Digital inputs','Bad Signal (SIG.AB) - simulation only, OFF by default')`);
rep(`function paint(){const sh=cs();if(!sh||!sh.S||!L)return;`,`function badMarks(){const sh=cs();if(!sh||!sh.S||!L||!L.gb||!L.gb.parentNode)return;const S=sh.S;let g=L.badg;if(!g||!g.isConnected){g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('pointer-events','none');g.setAttribute('id','badmarks');L.gb.parentNode.appendChild(g);L.badg=g;g._k=null}
 const list=S.blk.filter(b=>b.k==='AI'&&b.sig&&S.rt.st[b.sig.id]&&S.rt.st[b.sig.id].val>.5),key=list.map(b=>b.id).join(',');if(g._k===key)return;g._k=key;g.textContent='';
 for(const b of list){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',b.cx);t.setAttribute('y',-(b.y1!=null?b.y1:b.cy)-1.2);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','3.2');t.setAttribute('font-weight','700');t.setAttribute('fill','#ff5252');t.setAttribute('stroke','#000');t.setAttribute('stroke-width','.5');t.setAttribute('paint-order','stroke');t.textContent='FORCED BAD';g.appendChild(t)}}
function paint(){const sh=cs();if(!sh||!sh.S||!L)return;try{badMarks()}catch(e){}`);
rep(` whyRow(d,S,b);
 const P=b.p,pr=`,` whyRow(d,S,b);
 if(b.k==='AI'&&b.sig){const st=S.rt.st[b.sig.id],bt=h$('button',{title:'Simulation only. Forces the SIG.AB flag of this transmitter ON (FORCED BAD) or back to normal. Nothing is written to a DCS.'});bt.classList.add('wr');bt.onclick=()=>{st.val=st.val?0:1;(sv(sh).ai=sv(sh).ai||{})[b.sig.id]=st.val;anSave();settle()};const up=()=>{bt.textContent=st.val?'FORCED BAD (ON) - click to restore normal':'Bad Signal: OFF - click to force BAD';bt.classList.toggle('on',!!st.val)};up();PU.push(up);d.append(h$('div',{cls:'r'},[h$('span',{cls:'n',txt:'Bad Signal (SIG.AB) of this transmitter'}),bt]))}
 const P=b.p,pr=`);
/* High / low selector (HS, LS: findings 1 and 6): only the SELECTED input is lit, the other input wire is dimmed like the unselected leg of a T switch. The selected input = the one the engine passes (HS: the largest, LS: the smallest; ties: the first). */
rep(`function anDead(S){const dead=new Set()`,`function anHL(S,b){const v=S.rt.v;let bi=-1,bv=0;for(const n of b.i){const x=v[n];if(bi<0||(b.k==='HS'?x>bv:x<bv)){bi=n;bv=x}}return bi}
function anDead(S){const dead=new Set()`);
rep(`   for(const b of C){if((b.k==='SW'||b.k==='AMT')&&b.a>=0&&b.b>=0&&b.a!==b.b&&n===uns(b)&&n!==b.sel)continue;`,`   for(const b of C){if((b.k==='HS'||b.k==='LS')&&b.i.length>1&&b.i.includes(n)&&n!==anHL(S,b))continue;if((b.k==='SW'||b.k==='AMT')&&b.a>=0&&b.b>=0&&b.a!==b.b&&n===uns(b)&&n!==b.sel)continue;`);
rep(`dk+=q&&q.pk==='B'?'B':'A'}if(S._dk!==dk`,`dk+=q&&q.pk==='B'?'B':'A'}else if((b.k==='HS'||b.k==='LS')&&b.i.length>1)dk+=anHL(S,b)+',';if(S._dk!==dk`);
};
