/* v1.20.1: every ANALOG address text has its live value beside it (user 2026-10-08: "dapat address at wires"; then: "analog lang may LIVE value, ung digital kahit wala na" - digital stays as wire colour only).
   v1.20.0 audit (tools/audit-addr-values.js): 2316 address / tag texts on the 51 sheets, only 876 had a value beside them (277 analog and 1163 digital did not: the digital wires were only coloured, and a net with several texts got ONE badge).
   Now: for every text that names a wire (S.lab, S.tagN) a badge (1 / 0 for digital, number for analog) is placed at the end of THAT text unless a value of the same wire is already beside it. The badge belongs to the address: it is not a "bare wire value" (toggle Wire values does not hide it). */
module.exports=(rep)=>{
/* LINK TO THE DITL PAGE (user: "ung link sa DITL, di gumagana"): a "FROM / TO DITL pp-nn" reference opens the DITL page at sheet pp. From the DITL signals list (click the reference) and from the circle that carries the text (click the circle). The DITL page itself is not changed. */
rep(String.raw`function connClick(c){const sh=cs(),S=sh.S;AN.sel={net:c.nets[0]};selBox();paint();panelUpd(true);`,String.raw`function dsGoRef(r){const m=/(?:DITL\s*)?([0-9]{2}[A-Z]?)\s*-\s*(\d+)/i.exec(String(r));if(!m){msg('DITL reference not understood: '+r);return false}const code=m[1].toUpperCase(),nn=m[2];let i=S.sheets.findIndex(x=>new RegExp('DITL-'+code+'$','i').test(x.name));if(i<0)i=S.sheets.findIndex(x=>new RegExp('DITL-'+code.replace(/[A-Z]$/,'')+'$','i').test(x.name));if(i<0){msg('DITL sheet '+code+' ('+r+') is not in the DITL page');return false}setCat('dig');S.cur=i;sel=null;render();msg('DITL page: '+S.sheets[i].name+' (reference '+r+', item '+nn+')');return true}
function connClick(c){const sh=cs(),S=sh.S;AN.sel={net:c.nets[0]};selBox();paint();panelUpd(true);
 {const dt=S.tx.filter(t=>/DITL\s*[0-9]{2}[A-Z]?\s*-\s*\d+/i.test(t.t)&&Math.hypot(t.x-c.x,t.y-c.y)<c.r+30).sort((a,b)=>Math.hypot(a.x-c.x,a.y-c.y)-Math.hypot(b.x-c.x,b.y-c.y))[0];if(dt){const m=/DITL\s*([0-9]{2}[A-Z]?)\s*-\s*(\d+)/i.exec(dt.t);if(m&&dsGoRef('DITL '+m[1]+'-'+m[2]))return}}`);
rep(String.raw`cell(dir==='FROM'?'◀ FROM':'→ TO'),cell(refs.join(', ')),`,String.raw`cell(dir==='FROM'?'◀ FROM':'→ TO'),h$('td',{style:'padding:2px 6px;border-bottom:1px solid var(--line,#334)'},refs.map(r=>h$('a',{href:'#',txt:r,title:'Open the DITL page at this sheet',style:'margin-right:6px;color:var(--acc)',onclick:ev=>{ev.preventDefault();dsGoRef(r)}}))),`);
rep(String.raw` svg.append(g0,go_,gleg,gd,gfg,gf,gp,gt,gcj,L.selg,gb);
 const av=AN.av[sh.name];`,String.raw` {const done=new Set(),bx=q=>+q.t.getAttribute('x'),by=q=>-+q.t.getAttribute('y'),has=(n,x,y)=>L.bd.some(q=>q.n===n&&!q.wire&&!q.skip&&Math.hypot(bx(q)-x,by(q)-y)<45),put=(n,t,x,y,h)=>{if(n==null||!S.nets[n]||!S.nets[n].segs.length||S.nets[n].dig)return;/* user: only the ANALOG addresses have a live value; digital stays as colour */const k=n+'|'+t+'|'+Math.round(x)+'|'+Math.round(y);if(done.has(k))return;done.add(k);const ex=x+String(t).trim().length*(h||3)*.62+1.5;if(has(n,ex,y))return;
   const e=el('text',{x:ex,y:-(y+bs*.2),class:'bd'+(S.nets[n].dig?' dg':''),'text-anchor':'start'},gb);e.dataset.n=n;L.bd.push({n,t:e,last:null,skip:false,wire:false,addr:true})};
  S.lab.forEach((l,n)=>{if(l&&l.t)put(n,l.t,l.x,l.y,l.h)});(S.tagN||[]).forEach(q=>{const tx=S.tx.find(z=>z.t===q.t);if(tx)put(q.n,q.t,tx.x,tx.y,tx.h)})}
 svg.append(g0,go_,gleg,gd,gfg,gf,gp,gt,gcj,L.selg,gb);
 const av=AN.av[sh.name];`);
rep(String.raw`plOpen,plClose,plAIs,plRes,plVal});`,String.raw`plOpen,plClose,plAIs,plRes,plVal,dsGoRef,connClick});`);
};
