/* v1.16.1 WIP: COS = the operator's MANUAL value that enters a T / AMT switch (change-over). Before: the manual value of many COS was an unnamed wire ("PV", "B" ...), 83 of 173 COS had no control at all, and the value moved
   with the field-input ramp without telling.  Now every COS manual value is named by the wire the T switch drives (tag / address) with its description, shows its range and unit (taken from the drawing: the controller / manual station / transmitter on the auto leg),
   shows "target -> now" (the ramp is kept: the value goes to the target gradually), and is DISABLED when the COS is not energized (the T switch is on the auto leg), unless the T has no switching signal or its output is an SV / PV.
   Resolved COS: the one that provides the B leg of the T (attached) and the one that sits at a T whose B leg is an unnamed external wire. */
module.exports=(rep)=>{
rep(String.raw`function nm(S,n){const l=S.lab[n];if(l)return l.t;`,String.raw`function cosRange(S,e){const t=e.t,seen=new Set();let hit=null;const up=(n,d)=>{if(hit||d>6||n==null||n<0||seen.has(n))return;seen.add(n);for(const dr of S.drv[n]||[]){const b=S.blk.find(q=>q.id===dr.id);if(!b)continue;if(b.k==='MAN'&&b.p&&b.p.lo!=null){hit={lo:b.p.rlo!=null?b.p.rlo:b.p.lo,hi:b.p.rhi!=null?b.p.rhi:b.p.hi,u:b.p.u||'%'};return}if((b.k==='PID'||b.k==='PIDV')&&b.p){hit={lo:b.p.lo==null?0:b.p.lo,hi:b.p.hi==null?100:b.p.hi,u:'%'};return}for(const q of b.i||[])up(q,d+1)}};up(t.a,0);
 if(!hit){try{const r=anRange(S,{cx:e.c.cx,cy:e.c.cy},60);if(r&&r.hi>r.lo)hit={lo:r.lo,hi:r.hi,u:r.u||''}}catch(x){}}return hit||{lo:0,hi:100,u:'%'}}
function cosTarget(S,t){const seen=new Set();let fr=(t.o||[]).slice(),g=0;while(fr.length&&g++<6){const nx=[];for(const n of fr){if(seen.has(n))continue;seen.add(n);const l=S.lab[n];if(l&&l.t&&!/^COS manual/.test(l.t))return l.t;for(const b of S.cns[n]||[]){const tg=b.tag||((b.k==='PID'||b.k==='PIDV')?(b.txt||[])[1]:'');if(tg&&b!==t)return b.k+' '+tg;if(b.k==='AO'||b.k==='IP'){const o=(b.pins||[]).map(p=>S.lab[p.n]&&S.lab[p.n].t).find(Boolean);if(o)return o}for(const m of b.o||[])nx.push(m)}}fr=nx}return ''}
function cosInfo(S,n){if(!S._cm){const m=S._cm=new Map(),Ts=S.blk.filter(b=>b.k==='AMT'||b.k==='SW'),unres=S._cosUn=[];
  for(const c of S.blk){if(c.k!=='COS')continue;const t=c.used?S.blk.find(b=>b.id===c.tb):Ts.filter(x=>Math.hypot(x.cx-c.cx,x.cy-c.cy)<30).sort((p,q)=>Math.hypot(p.cx-c.cx,p.cy-c.cy)-Math.hypot(q.cx-c.cx,q.cy-c.cy))[0];
   if(t){const net=c.used?c.vnet:(t.b>=0&&S.ext.includes(t.b)?t.b:null);if(net!=null&&!m.has(net)){m.set(net,{c,t,net,kind:'T',dig:!!S.nets[net].dig});continue}}
   /* COS beside a PID: the external wire that enters the SV (+) input of the DEV in front of the PID is the operator's SV */
   const dv=S.blk.filter(x=>x.k==='DEV'&&Math.hypot(x.cx-c.cx,x.cy-c.cy)<45).sort((p,q)=>Math.hypot(p.cx-c.cx,p.cy-c.cy)-Math.hypot(q.cx-c.cx,q.cy-c.cy));let done=false;
   for(const d of dv){const pl=(d.ip||[]).find(q=>q.sg>0);if(pl&&S.ext.includes(pl.n)&&!S.nets[pl.n].dig&&!m.has(pl.n)){const pid=(S.cns[d.o[0]]||[]).find(x=>x.k==='PID'||x.k==='PIDV');m.set(pl.n,{c,t:null,dev:d,pid,net:pl.n,kind:'SV',dig:false});done=true;break}}
   if(!done)unres.push(c)}}
 const e=S._cm.get(n);if(!e)return null;if(!e.name){if(e.kind==='SV'){const tg=e.pid?((e.pid.txt||[])[1]||e.pid.k):'';e.name='COS manual SV ▸ '+(tg||'PID');e.out=tg;const P=e.pid&&e.pid.p||{};e.rng=P.rlo!=null?{lo:P.rlo,hi:P.rhi,u:P.unit||''}:{lo:0,hi:100,u:'%'}}
  else{e.out=cosTarget(S,e.t);e.name='COS manual'+(e.dig?' (on / off)':'')+' ▸ '+(e.out||('T'+e.t.id));e.rng=e.dig?{lo:0,hi:1,u:''}:cosRange(S,e)}}return e}
function cosOn(S,e){if(e.kind==='SV')return{on:true,why:'operator SV of the controller: always settable'};const t=e.t,st=S.rt.st[t.id]||{},sw=t.sel>=0||(t.cs&&t.cs.length);if(!sw)return{on:true,why:'this T has no switching signal: always a manual input'};
 const o=(t.o||[])[0];if(o!=null&&(S.cns[o]||[]).some(x=>x.k==='DEV'||x.k==='PID'||x.k==='PIDV'))return{on:true,why:'used as SV / PV: always settable'};
 const on=st.pk==='B',sn=t.sel>=0?(nm(S,t.sel)+' = '+(S.rt.v[t.sel]>.5?1:0)):(t.cs&&t.cs.length?'COS select':'');return{on,why:(on?'ENERGIZED: the T switch is on the manual leg':'NOT ENERGIZED: the T switch is on the auto (A) leg, the manual value is not used')+(sn?' · switching: '+sn:'')}}
function cosCtl(S,sh,n,e){if(e.dig){const bx=h$('span',{cls:'fc',style:'flex-wrap:wrap'}),bt=h$('button',{}),wy=h$('small',{style:'flex-basis:100%;color:#9ab'}),ad0=adesFind(sh,e.out||''),ds0=ad0?adesText(ad0.rec):'';bt.onclick=()=>{if(!cosOn(S,e).on)return;const v=S.rt.ext[n]>.5?0:1;S.rt.ext[n]=v;(sv(sh).ext=sv(sh).ext||{})[n]=v;anSave();settle()};bx.append(bt,wy);const u0=()=>{const o=cosOn(S,e),on=S.rt.ext[n]>.5;bt.textContent=on?'INPUT 1 · ON':'INPUT 0 · OFF';bt.classList.toggle('on',on);bt.disabled=!o.on;bx.style.opacity=o.on?1:.5;wy.textContent=(ds0?ds0+' · ':'')+o.why;wy.style.color=o.on?'#8fe3b0':'#ffb04d'};u0();u0._s=1;PU.push(u0);return bx}const r=e.rng,box=h$('span',{cls:'fc',style:'flex-wrap:wrap'}),i=anEdit(h$('input',{type:'number',step:'any'})),rg=h$('input',{type:'range',min:r.lo,max:r.hi,step:(r.hi-r.lo)/1000}),ok=h$('button',{txt:'✓',title:'Accept this value (Enter)'}),st=h$('small',{style:'flex-basis:100%'}),why=h$('small',{style:'flex-basis:100%;color:#9ab'}),ad=adesFind(sh,e.out||''),ds=ad?adesText(ad.rec):'';
 i.style.width='74px';rg.style.width='100%';const set=v=>{if(!cosOn(S,e).on)return;S.rt.ext[n]=v;(sv(sh).ext=sv(sh).ext||{})[n]=v;anSave();settle()},acc=()=>{const v=parseFloat(i.value);if(isFinite(v)){i._clr();set(Math.max(r.lo,Math.min(r.hi,v)))}};ok.onclick=acc;i.onkeydown=ev=>{if(ev.key==='Enter'){ev.preventDefault();acc()}};rg.oninput=()=>set(+rg.value);
 box.append(h$('small',{txt:'range '+fmt(r.lo)+' ~ '+fmt(r.hi)+' '+r.u+(ds?' · '+ds:''),style:'flex-basis:100%;color:#9ab'}),i,ok,rg,st,why);
 const u=()=>{const o=cosOn(S,e);i.disabled=rg.disabled=ok.disabled=!o.on;box.style.opacity=o.on?1:.5;why.textContent=o.why;why.style.color=o.on?'#8fe3b0':'#ffb04d';const tgt=S.rt.ext[n]||0,now=S.rt.v[n];st.textContent='target '+fmt(tgt)+' → now '+fmt(now)+' '+r.u+(Math.abs(tgt-(now==null?0:now))>1e-6*(1+Math.abs(tgt))?'  (ramping)':'');if(document.activeElement!==i&&!i._d)i.value=tgt;if(document.activeElement!==rg)rg.value=tgt};u();u._s=1;PU.push(u);return box}
function nm(S,n){{const ci=cosInfo(S,n);if(ci)return ci.name}const l=S.lab[n];if(l)return l.t;`);
rep(String.raw`const ctl=(S,sh,n)=>S.ext.includes(n)&&!(S.xlk&&S.xlk[n])?inCtl(S,sh,n):forceCtl(S,sh,n);`,String.raw`const ctl=(S,sh,n)=>{const e=cosInfo(S,n);if(e&&S.ext.includes(n)&&!(S.xlk&&S.xlk[n]))return cosCtl(S,sh,n,e);return S.ext.includes(n)&&!(S.xlk&&S.xlk[n])?inCtl(S,sh,n):forceCtl(S,sh,n)};`);
rep(String.raw`trMap,trGoCrumb,hmiAdd,`,String.raw`trMap,trGoCrumb,cosInfo,cosOn,hmiAdd,`);
};
