/* v1.16.1 WIP: COS = the OPERATOR's manual value / change-over that enters the logic. Every COS of the drawings (173) is now found and named:
   - T: a COS at a T / AMT switch that provides its B leg (analog or on / off) or sits at a T whose B leg is an external wire;
   - W: a COS whose diamond touches an external wire (operator SV or PV of a controller, a ratio, a limit: "RANGE : 0.01 ~ 9.99 %" is read from the drawing);
   - L: a COS at a T whose B leg is driven by the logic (the A / M change-over comes from the switching logic: shown as a STATUS, not a control).
   Each one shows: the name of what it controls (tag / address), its description (loop description of the DCS file, memory list), range and unit (drawing text, controller, manual station), "target -> now" (the ramp is kept),
   and it is DISABLED while it is not energized (the T switch is on the auto leg), except when it is the SV / PV of a controller or has no switching signal.
   The panel gets a section "COS" that lists them all, and nm() gives their names everywhere (trace, trend, HMI). */
module.exports=(rep)=>{
rep(String.raw`function nm(S,n){const l=S.lab[n];if(l)return l.t;`,String.raw`function cosFromNets(S,nets,self){const seen=new Set();let fr=nets.slice(),g=0;while(fr.length&&g++<6){const nx=[];for(const n of fr){if(seen.has(n))continue;seen.add(n);const l=S.lab[n];if(l&&l.t&&!/^COS/.test(l.t)&&n!==nets[0])return l.t;for(const b of S.cns[n]||[]){const tg=b.tag||((b.k==='PID'||b.k==='PIDV')?(b.txt||[])[1]:'');if(tg&&b!==self)return b.k+' '+tg;if(b.k==='AO'||b.k==='IP'){const o=(b.pins||[]).map(p=>S.lab[p.n]&&S.lab[p.n].t).find(Boolean);if(o)return o}for(const m of b.o||[])nx.push(m)}}fr=nx}return ''}
function cosRange(S,e){const t=e.t,seen=new Set();let hit=null;const up=(n,d)=>{if(hit||d>6||n==null||n<0||seen.has(n))return;seen.add(n);for(const dr of S.drv[n]||[]){const b=S.blk.find(q=>q.id===dr.id);if(!b)continue;if(b.k==='MAN'&&b.p&&b.p.lo!=null){hit={lo:b.p.rlo!=null?b.p.rlo:b.p.lo,hi:b.p.rhi!=null?b.p.rhi:b.p.hi,u:b.p.u||'%'};return}if((b.k==='PID'||b.k==='PIDV')&&b.p){hit={lo:b.p.lo==null?0:b.p.lo,hi:b.p.hi==null?100:b.p.hi,u:'%'};return}for(const q of b.i||[])up(q,d+1)}};if(t)up(t.a,0);
 if(!hit){try{const r=anRange(S,{cx:e.c.cx,cy:e.c.cy},60);if(r&&r.hi>r.lo)hit={lo:r.lo,hi:r.hi,u:r.u||''}}catch(x){}}return hit||{lo:0,hi:100,u:'%'}}
function cosInfo(S,n){if(!S._cm){const m=S._cm=new Map(),all=S._cosAll=[],Ts=S.blk.filter(b=>b.k==='AMT'||b.k==='SW'),unres=S._cosUn=[],ds=(px,py,s)=>{const dx=s.x2-s.x1,dy=s.y2-s.y1,l2=dx*dx+dy*dy;let t=l2?((px-s.x1)*dx+(py-s.y1)*dy)/l2:0;t=Math.max(0,Math.min(1,t));return Math.hypot(px-(s.x1+t*dx),py-(s.y1+t*dy))};
  for(const c of S.blk){if(c.k!=='COS')continue;const t=c.used?S.blk.find(b=>b.id===c.tb):Ts.filter(x=>Math.hypot(x.cx-c.cx,x.cy-c.cy)<30).sort((p,q)=>Math.hypot(p.cx-c.cx,p.cy-c.cy)-Math.hypot(q.cx-c.cx,q.cy-c.cy))[0];let e=null;
   if(t){const net=c.used?c.vnet:(t.b>=0&&S.ext.includes(t.b)?t.b:null);if(net!=null&&!m.has(net))e={c,t,net,kind:'T',dig:!!S.nets[net].dig}}
   if(!e){/* an external wire that touches the diamond */const ws=S.nets.filter(nn=>nn.segs.length&&S.ext.includes(nn.id)&&!m.has(nn.id)&&!(S.xlk&&S.xlk[nn.id])&&nn.segs.some(i=>ds(c.cx,c.cy,S.seg[i])<16)).map(nn=>({nn,d:Math.min(...nn.segs.map(i=>ds(c.cx,c.cy,S.seg[i])))})).sort((p,q)=>p.d-q.d);
    if(ws.length){const nn=ws[0].nn;const dv=S.blk.filter(x=>x.k==='DEV').find(x=>(x.ip||[]).some(q=>q.n===nn.id)),sg=dv&&dv.ip.find(q=>q.n===nn.id).sg,pid=dv&&(S.cns[dv.o[0]]||[]).find(x=>x.k==='PID'||x.k==='PIDV');e={c,t:null,dev:dv,pid,net:nn.id,kind:'W',role:dv?((pid&&anPins(S,pid))?(anPins(S,pid).sv===nn.id?'SV':'PV'):(sg>0?'SV':'PV')):'',dig:!!nn.dig}}}
   if(!e&&t&&t.b>=0&&!S.ext.includes(t.b))e={c,t,net:null,kind:'L',dig:!!S.nets[t.b].dig,sel:t.b};
   if(!e){unres.push(c);continue}all.push(e);if(e.net!=null)m.set(e.net,e)}}
 const e=n===-99?null:S._cm.get(n);if(!e)return null;return cosFill(S,e)}
function cosFill(S,e){if(e.name)return e;
 if(e.kind==='L'){const o=(e.t.o||[])[0],on=o!=null?cosFromNets(S,[o],e.t):'',sn=e.sel>=0&&S.lab[e.sel]?S.lab[e.sel].t:('net '+e.sel);e.out=on;e.name='COS change-over ▸ '+(on||('T'+e.t.id))+' (switched by '+sn+')';e.rng=null;return e}
 if(e.kind==='W'){const l=S.lab[e.net],P=(e.pid&&e.pid.p)||{},tg=e.pid?((e.pid.txt||[])[1]||e.pid.k):'';e.out=tg||cosFromNets(S,[e.net],null);
  e.name='COS manual '+(e.role?e.role+' ':'')+'▸ '+(l&&l.t?l.t:(e.out||'wire '+e.net));
  if(e.pid&&P.rlo!=null)e.rng={lo:P.rlo,hi:P.rhi,u:P.unit||''};else{let r=null;try{r=anRange(S,{cx:e.c.cx,cy:e.c.cy},45)}catch(x){}e.rng=r&&r.hi>r.lo?{lo:r.lo,hi:r.hi,u:r.u||''}:{lo:0,hi:100,u:'%'}}return e}
 e.out=cosFromNets(S,e.t.o||[],e.t);e.name='COS manual'+(e.dig?' (on / off)':'')+' ▸ '+(e.out||('T'+e.t.id));e.rng=e.dig?{lo:0,hi:1,u:''}:cosRange(S,e);return e}
function cosDesc(S,sh,e){let d='';const tag=e.pid?((e.pid.txt||[])[1]||''):'',F=typeof AN_DEF!=='undefined'&&AN_DEF.FACE;
 const find=t=>{if(!F||!t)return '';for(const k of['PID','MAN','SUMA'])for(const q of F[k]||[])if(q.tag===t&&q.desc)return q.desc;return ''};
 d=find(tag)||find((e.out||'').replace(/^(PID|PIDV|MAN) /,''));if(!d){const a=adesFind(sh,(e.out||'').replace(/^[A-Z]+ /,''));if(a)d=adesText(a.rec)}
 if(!d&&e.pid)d=(S._shTitle||'');return d}
function cosOn(S,e){if(e.kind==='SV'||(e.kind==='W'&&e.role))return{on:true,why:'operator '+(e.role||'SV')+' of the controller: always settable'};if(e.kind==='W')return{on:true,why:'operator value: always settable'};const t=e.t,st=S.rt.st[t.id]||{},sw=t.sel>=0||(t.cs&&t.cs.length);
 if(e.kind==='L'){const on=st.pk==='B';return{on,why:(on?'ENERGIZED (manual leg selected)':'NOT ENERGIZED (auto leg selected)')+' · switched by the logic: '+(S.lab[e.sel]?S.lab[e.sel].t:'net '+e.sel)+' = '+(S.rt.v[e.sel]>.5?1:0)}}
 if(!sw)return{on:true,why:'this T has no switching signal: always a manual input'};const o=(t.o||[])[0];if(o!=null&&(S.cns[o]||[]).some(x=>x.k==='DEV'||x.k==='PID'||x.k==='PIDV'))return{on:true,why:'used as SV / PV: always settable'};
 const on=st.pk==='B',sn=t.sel>=0?(nm(S,t.sel)+' = '+(S.rt.v[t.sel]>.5?1:0)):(t.cs&&t.cs.length?'COS select':'');return{on,why:(on?'ENERGIZED: the T switch is on the manual leg':'NOT ENERGIZED: the T switch is on the auto (A) leg, the manual value is not used')+(sn?' · switching: '+sn:'')}}
function cosCtl(S,sh,n,e){const ds=cosDesc(S,sh,e);if(e.dig){const bx=h$('span',{cls:'fc',style:'flex-wrap:wrap'}),bt=h$('button',{}),wy=h$('small',{style:'flex-basis:100%;color:#9ab'});bt.onclick=()=>{if(!cosOn(S,e).on)return;const v=S.rt.ext[n]>.5?0:1;S.rt.ext[n]=v;(sv(sh).ext=sv(sh).ext||{})[n]=v;anSave();settle()};bx.append(h$('small',{txt:ds,style:'flex-basis:100%;color:#9ab'}),bt,wy);const u0=()=>{const o=cosOn(S,e),on=S.rt.ext[n]>.5;bt.textContent=on?'INPUT 1 · ON':'INPUT 0 · OFF';bt.classList.toggle('on',on);bt.disabled=!o.on;bx.style.opacity=o.on?1:.5;wy.textContent=o.why;wy.style.color=o.on?'#8fe3b0':'#ffb04d'};u0();u0._s=1;PU.push(u0);return bx}
 const r=e.rng,box=h$('span',{cls:'fc',style:'flex-wrap:wrap'}),i=anEdit(h$('input',{type:'number',step:'any'})),rg=h$('input',{type:'range',min:r.lo,max:r.hi,step:(r.hi-r.lo)/1000}),ok=h$('button',{txt:'✓',title:'Accept this value (Enter)'}),st=h$('small',{style:'flex-basis:100%'}),why=h$('small',{style:'flex-basis:100%;color:#9ab'});
 i.style.width='74px';rg.style.width='100%';const set=v=>{if(!cosOn(S,e).on)return;S.rt.ext[n]=v;(sv(sh).ext=sv(sh).ext||{})[n]=v;anSave();settle()},acc=()=>{const v=parseFloat(i.value);if(isFinite(v)){i._clr();set(Math.max(r.lo,Math.min(r.hi,v)))}};ok.onclick=acc;i.onkeydown=ev=>{if(ev.key==='Enter'){ev.preventDefault();acc()}};rg.oninput=()=>set(+rg.value);
 box.append(h$('small',{txt:'range '+fmt(r.lo)+' ~ '+fmt(r.hi)+' '+r.u+(ds?' · '+ds:''),style:'flex-basis:100%;color:#9ab'}),i,ok,rg,st,why);
 const u=()=>{const o=cosOn(S,e);i.disabled=rg.disabled=ok.disabled=!o.on;box.style.opacity=o.on?1:.5;why.textContent=o.why;why.style.color=o.on?'#8fe3b0':'#ffb04d';const tgt=S.rt.ext[n]||0,now=S.rt.v[n];st.textContent='target '+fmt(tgt)+' → now '+fmt(now)+' '+r.u+(Math.abs(tgt-(now==null?0:now))>1e-6*(1+Math.abs(tgt))?'  (ramping)':'');if(document.activeElement!==i&&!i._d)i.value=tgt;if(document.activeElement!==rg)rg.value=tgt};u();u._s=1;PU.push(u);return box}
function cosStatus(S,sh,e){const box=h$('span',{cls:'fc',style:'flex-wrap:wrap'}),w=h$('small',{style:'flex-basis:100%'}),ds=cosDesc(S,sh,e);box.append(h$('small',{txt:(ds?ds+' · ':'')+'A / M change-over by the switching logic (not a manual value)',style:'flex-basis:100%;color:#9ab'}),w);const u=()=>{const o=cosOn(S,e);w.textContent=o.why;w.style.color=o.on?'#8fe3b0':'#ffb04d'};u();u._s=1;PU.push(u);return box}
function nm(S,n){{const ci=cosInfo(S,n);if(ci)return ci.name}const l=S.lab[n];if(l)return l.t;`);
rep(String.raw`const ctl=(S,sh,n)=>S.ext.includes(n)&&!(S.xlk&&S.xlk[n])?inCtl(S,sh,n):forceCtl(S,sh,n);`,String.raw`const ctl=(S,sh,n)=>{const e=cosInfo(S,n);if(e&&S.ext.includes(n)&&!(S.xlk&&S.xlk[n]))return cosCtl(S,sh,n,e);return S.ext.includes(n)&&!(S.xlk&&S.xlk[n])?inCtl(S,sh,n):forceCtl(S,sh,n)};`);
/* a section that lists every COS of the sheet */
rep(String.raw` /* every wire that a block drives and that has a tag, plus the outputs of AO / I/P / controllers / switches: FORCE from here`,String.raw` /* COS: every operator manual value / change-over of this sheet */
 try{cosInfo(S,-99);for(const e of S._cosAll||[]){cosFill(S,e);const ce=e.net!=null?[ctl(S,sh,e.net)]:[cosStatus(S,sh,e)];mkRow(grp('COS · manual values and change-overs',''),'c'+e.c.id,e.name,'',ce,{x:e.c.cx,y:e.c.cy})}}catch(x){}
 /* every wire that a block drives and that has a tag, plus the outputs of AO / I/P / controllers / switches: FORCE from here`);
rep(String.raw`trMap,trGoCrumb,hmiAdd,`,String.raw`trMap,trGoCrumb,cosInfo,cosOn,cosFill,hmiAdd,`);
};
