/* Closed loop of every PID / PIDV with a simple process model (no plant exists in the simulator): deviation = SV - PV in engineering units, PV follows the PID output through a first order lag (time constant by loop type, gain 1: every 100 % of output moves the span (centred on the middle of the output range ML ~ MH of the DCS faceplate)); the sign of the process follows the action of the PID (reverse = more output raises PV).  The SV is stepped 20 % of the span; the loop must settle (|deviation| < 3 % of span at the end of max(900 s, 8 x Ti)) without growing oscillations and the output must stay inside its range. This tests the DEFAULT tuning, which is not the plant's real tuning (docs/ASSUMED-VALUES.md).  usage: node tools/test-loops.js file.html */
const {load,build}=require('./lib.js');const {E,rows}=load(process.argv[2]);let tot=0,ok=0;const bad=[],info=[];
const TAU={flow:6,pressure:25,temperature:60,level:90,analysis:40,speed:15,general:30};
for(const r of rows){if(/ABC-000/.test(r.name))continue;const S=build(E,r);
 for(const b of S.blk){if(b.k!=='PID'&&b.k!=='PIDV')continue;const o=b.o.find(n=>(S.cns[n]||[]).length&&S.nets[n].segs.length);if(b.in0==null||b.in0<0||o==null)continue;tot++;
  for(const t of S.blk)if((t.k==='AMT'||t.k==='SW')&&(t.trkFrom||[]).includes(b)){const reach=n=>{const seen=new Set(),q=[o];while(q.length){const x=q.pop();if(x===n)return true;if(seen.has(x))continue;seen.add(x);for(const c of S.cns[x]||[])for(const y of c.o||[])q.push(y);for(const[d,s2]of S.link||[])if(s2===x)q.push(d)}return false};S.rt.st[t.id].fm=reach(t.a)?'A':reach(t.b)?'B':null}
  const span=b.p.span>0?b.p.span:100,lo=b.p.lo==null?0:b.p.lo,hi=b.p.hi==null?100:b.p.hi,sgn=(b.p.act==null?-1:b.p.act)<0?1:-1,tau=TAU[b.p.lt||'general']||30,dt=.5;
  let pv=0.3*span,sv=0.3*span,pv0=pv;S.rt.force={};const dev=()=>sv-pv;S.rt.force[b.in0]=dev();E.anSettle(S,5);for(let i=0;i<200;i++){S.rt.force[b.in0]=dev();E.anStep(S,dt);const u=S.rt.v[o];pv+=dt/tau*(sgn*(u-(lo+hi)/2)/100*span+0.3*span-pv)}
  sv=0.5*span;let maxo=-1e9,mino=1e9,devs=[];const N=Math.round(Math.max(900,8*(b.p.ti||0))/dt);for(let i=0;i<N;i++){S.rt.force[b.in0]=dev();E.anStep(S,dt);const u=S.rt.v[o];maxo=Math.max(maxo,u);mino=Math.min(mino,u);pv+=dt/tau*(sgn*(u-(lo+hi)/2)/100*span+0.3*span-pv);devs.push(Math.abs(dev())/span)}
  const endDev=devs.slice(-200).reduce((a,c)=>Math.max(a,c),0),mid=devs.slice(Math.round(N/2),Math.round(N/2)+200).reduce((a,c)=>Math.max(a,c),0);
  const inRange=maxo<=hi+1e-6&&mino>=lo-1e-6;const id=r.name+' '+b.k+'#'+b.id+' '+(b.tag||'')+' ('+(b.p.lt||'general')+', Kp '+b.p.kp+' Ti '+b.p.ti+', act '+b.p.act+')';
  const settled=endDev<.03,growing=endDev>mid*1.5+.01;
  const trim=(hi-lo)<60;/* trim / bias outputs (PIC-COBM -25 ~ 25, AICFG10571 10 ~ 35): the process gain behind them is unknown, only 'bounded and inside the output range' is checked */if(((settled&&!growing)||(trim&&!growing))&&inRange)ok++;else bad.push(id+' end |dev| '+(100*endDev).toFixed(1)+' % of span, mid '+(100*mid).toFixed(1)+' %, output '+mino.toFixed(1)+' .. '+maxo.toFixed(1))}}
console.log('PID / PIDV in a closed loop with a simple process:',tot,'| settle without growing oscillation, output in range:',ok,'| problems:',bad.length);bad.forEach(x=>console.log('  '+x))
