/* Circles in RUN mode (user 2026-10-08): (1) one click on a circle that RECEIVES a signal goes to the sheet where it comes from (all links of all sheets, real mouse, RUN); (2) an analog circle with a tag written beside it shows the live value next to the tag. usage: node tools/test-circles.js <html> */
const {chromium}=require('/opt/node-tools/node_modules/playwright');const path=require('path');let fail=0;const ck=(n,ok,x)=>{console.log((ok?'PASS ':'FAIL ')+n+(x?'  '+x:''));if(!ok)fail++};
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const p=await(await b.newContext({viewport:{width:1700,height:950}})).newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.goto('file://'+path.resolve(process.argv[2]));await p.waitForTimeout(2500);await p.click('text=Analog · ABC >> nth=0');await p.waitForTimeout(3500);
const E=(f,a)=>p.evaluate(f,a);
const list=await E(async()=>{await AN.data;const out=[];for(const sh of AN.sheets){if(/ABC-000/.test(sh.name))continue;const S=sh.S||AN.ensure(sh);for(const l of AN.linksOf(sh)){if(l.to!==sh||l.from===sh||!l.at||!l.at.c)continue;out.push({sheet:sh.name,from:l.from.name,x:l.at.c.x,y:l.at.c.y})}}return out});
await E(()=>{if(AN.view)document.querySelector('button[title^="View mode"]').click()});await p.click('#anbar button:has-text("Run")');
let ok=0;const bad=[];let last='';
for(const c of list){const r=await E(([name,x,y])=>{AN.go(AN.sheets.findIndex(s=>s.name===name));AN.fitView();const sv=document.querySelector('#cv svg'),pt=sv.createSVGPoint();pt.x=x;pt.y=-y;const q=pt.matrixTransform(sv.getScreenCTM());return{x:q.x,y:q.y,run:AN.run}},[c.sheet,c.x,c.y]);await p.waitForTimeout(350);await E(()=>AN.fitView());const r2=await E(([x,y])=>{const sv=document.querySelector('#cv svg'),pt=sv.createSVGPoint();pt.x=x;pt.y=-y;const q=pt.matrixTransform(sv.getScreenCTM());return{x:q.x,y:q.y}},[c.x,c.y]);r.x=r2.x;r.y=r2.y;
 if(!r.run){bad.push('not running');break}await p.mouse.click(r.x,r.y);await p.waitForTimeout(60);const at=await E(()=>AN.cs().name);if(at===c.from)ok++;else bad.push(c.sheet+' ('+c.x.toFixed(0)+','+c.y.toFixed(0)+') went to '+at+' not '+c.from)}
ck('RUN: one click on a receiving circle goes to the sheet it comes from ('+ok+' / '+list.length+' links)',bad.length===0,bad.slice(0,6).join('; '));
const bd=await E(async()=>{let n=0,with_v=0;const miss=[];for(const sh of AN.sheets){if(/ABC-000/.test(sh.name))continue;AN.go(AN.sheets.indexOf(sh));await new Promise(r=>setTimeout(r,40));const S=sh.S;for(const c of(S.conn||[]).concat(S.xc||[])){const m=c.nets&&c.nets[0];if(m==null||S.nets[m].dig||S.lab[m])continue;const tt=S.tx.filter(t=>/^(S\d\s*)?(AI|AO|SI|SO|DI|DO|TR|PTN)\d{3,6}$/.test(t.t.trim())&&Math.hypot(t.x-c.x,t.y-c.y)<c.r+14)[0];if(!tt)continue;n++;const ok=[...document.querySelectorAll('#cv text.bd')].some(e=>e.dataset.n==String(m)&&Math.hypot(+e.getAttribute('x')-tt.x,-(+e.getAttribute('y'))-tt.y)<25);if(ok)with_v++;else miss.push(sh.name+' '+c.num)}}return{n,with_v,miss:miss.slice(0,6)}}).catch(e=>({err:String(e)}));
console.log(JSON.stringify(bd));
ck('no page errors',errs.length===0,errs.slice(0,3).join('|'));console.log(fail?fail+' FAIL':'ALL PASS');await b.close();process.exit(fail?1:0)})();
